# Generated by Django 6.0 on 2025-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["-loan_date"],
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
